<a href="https://colab.research.google.com/github/siomaradelcid-lab/datasci_1_loading/blob/main/HHA_507_Coding_Exercise_1_Siomara_Delcid.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

The following code cell below imports pandas

We needs pandas because we cannot load our datasets without it

These are the paths used for this exercise

2 CSV:

1. /content/HHA 507/ HW 1/Inpatient_Rehabilitation_Facility-General_Information_Sep2026.csv

2. /content/HHA 507/ HW 1/Inpatient_Rehabilitation_Facility-National_Data_Sep2026.csv

3 Excel:

1. /content/HHA 507/ HW 1/emergency-department-volume-and-capacity-2021-2023.xlsx

2. /content/HHA 507/ HW 1/supplier-diversity-in-california-hospital-procurements-2021-2023-data-dictionary.xlsx

3. /content/HHA 507/ HW 1/hci_unemployment_290_ca_re_co_cd_pl_ct-5-22-14-ada.xlsx

3 Json:

1. /content/HHA 507/ HW 1/MTA_Data.json

2. /content/HHA 507/ HW 1/MTA delays.json

3. /content/HHA 507/ HW 1/MTA_LIRR incidents.json

In [4]:
import pandas as pd

CMS Inpatient Rehabilitation Facility - General Information

This dataset shows characteristics of the inpatient rehabilitation facilities that are shown on Inpatient Rehabilitation Facility Compare.

**Columns**

**1. CMS Certifaction Number (CCN)**

* contains list of unique six digit ID codes assigned by the centers of medicare & medicaid services (CMS).

**2. Provider Name**
* lists the names of every rehab center in the dataset

**3. Address Line**

* lists the physical location of the rehab center

**4. Address Line 2**
* lists any additional addresses related to a specific rehab center

**5. City/Town**
* lists which city or town the rehab center is located

**6. State**
* List the state it is in

**7. Zip Code**
* unique 5 number code of where the rehab center is located in

**8. County/Parish**
* lists which county it is located in

**9. Telephone number**
* list the phone number of every facility

**10. CMS region**
* region number assigned to each facility

**11. Ownership Type**
* lists if the facility is nonprofit, for profit, or governemnt

**12. Certification Data**
* lists when each facility recieved its certification

In [16]:
Gen_info = '/content/HHA 507/ HW 1/Inpatient_Rehabilitation_Facility-General_Information_Sep2026.csv'
read_Gen_info = pd.read_csv(Gen_info)
read_Gen_info.head(11)

,CMS Certification Number (CCN),Provider Name,Address Line 1,Address Line 2,City/Town,State,ZIP Code,County/Parish,Telephone Number,CMS Region,Ownership Type,Certification Date
0,013025,ENCOMPASS HEALTH LAKESHORE REHABILITATION HOSP...,3800 RIDGEWAY DRIVE,-,BIRMINGHAM,AL,35209,Jefferson,(205) 868-2000,4,For profit,10/01/1983
1,013028,ENCOMPASS REHABILITATION HOSPITAL OF MONTGOMERY,4465 NARROW LANE RD,-,MONTGOMERY,AL,36116,Montgomery,(334) 284-7821,4,For profit,05/11/1987
2,013029,ENCOMPASS HEALTH REHABILITATION HOSPITAL NORTH AL,1490 HIGHWAY 72 E,-,HUNTSVILLE,AL,35811,Madison,(205) 535-2300,4,For profit,06/04/1987
3,013030,ENCOMPASS HEALTH REHABILITATION HOSPITAL OF DO...,1736 EAST MAIN STREET,-,DOTHAN,AL,36301,Houston,(334) 712-6333,4,For profit,05/12/1994
4,013031,ENCOMPASS HEALTH REHABILITATION HOSPITAL OF SH...,900 OAK MOUNTAIN COMMONS LANE,-,PELHAM,AL,35124,Shelby,(205) 216-7621,4,For profit,05/25/2018
5,013032,ENCOMPASS HEALTH REHABILITATION HOSPITAL GADSDEN,801 GOODYEAR AVE,-,GADSDEN,AL,35903,Etowah,(256) 439-5000,4,For profit,08/14/2001
6,013033,REHABILITATION HOSPITAL OF PHENIX CITY,3715 US HIGHWAY 431 NORTH,-,PHENIX CITY,AL,36867,Russell,(334) 732-2200,4,For profit,11/12/2003
7,01T011,ST. VINCENTS EAST REHABILITATION CENTER,50 MEDICAL PARK EAST DRIVE,-,BIRMINGHAM,AL,35235,Jefferson,(205) 838-3672,4,Non-profit,04/30/1998
8,01T029,EAMC- LANIER,2000 PEPPERELL PARKWAY.,-,OPELIKA,AL,36801,Lee,(502) 596-6346,4,Government,10/01/2016
9,01T033,SPAIN REHABILITATION CENTER,SRC 223E,-,BIRMINGHAM,AL,35249,Jefferson,(205) 934-4940,4,Government,10/01/1997
10,01T092,DCH REHABILITATION CENTER,"809 UNIVERSITY BLVD, EAST",-,TUSCALOOSA,AL,35401,Tuscaloosa,(205) 333-4362,4,Government,05/01/2011

Inpatient Rehabilitation Facility - National Data
National data on the quality of patient care measures shown on Inpatient Rehabilitation Facility Compare.

Columns

**1. CMS Certification Number (CCN)**

* identifies the facility associated with the data. Because this dataset contains national-level data rather than individual facilities, this field is listed as “Nation.”

**2. Measure code**

* A unique code that identifies the specific CMS quality measure being reported. It combines the CMS measure ID with information identifying the type of score.

**3. Score**

* The national score or value reported for the corresponding quality measure.

**4. Footnote**

* Indicates whether a footnote or additional explanation applies to the reported measure. CMS currently reports no footnotes for the national data.

**5. Start Date**

* The beginning date of the reporting period used to calculate the measure and its score.

**6. End date**

* The ending date of the reporting period used to calculate the measure and its score.

**7. Measure Data Range**

* Shows the full reporting period associated with the measure and score. If the reporting period is split into separate time periods, the ranges are separated by a semicolon.

In [8]:
Nat_info='/content/HHA 507/ HW 1/Inpatient_Rehabilitation_Facility-National_Data_Sep2026.csv'
read_Nat_info = pd.read_csv(Nat_info)
read_Nat_info.head(11)

,CMS Certification Number (CCN),Measure Code,Score,Footnote,Start Date,End Date,Measure Date Range
0,NATION,I_006_01_NATL_SIR,1.000,-,10/01/2024,09/30/2025,-
1,NATION,I_011_05_NATL_OBS_RATE,65.26,-,01/01/2025,12/31/2025,-
2,NATION,I_012_06_NATL_OBS_RATE,62.48,-,01/01/2025,12/31/2025,-
3,NATION,I_013_01_NATL_OBS_RATE,0.15,-,01/01/2025,12/31/2025,-
4,NATION,I_015_01_NATL_SIR,0.340,-,10/01/2024,09/30/2025,-
5,NATION,I_016_01_NATL_OBS_RATE,77.10,-,10/01/2024,03/31/2025,-
6,NATION,I_017_01_PPR_PD_NATL_OBS_RATE,9.43,-,10/01/2023,09/30/2025,-
7,NATION,I_017_01_PPR_PD_N_BETTER_NATL,31,-,10/01/2023,09/30/2025,-
8,NATION,I_017_01_PPR_PD_N_NO_DIFF_NATL,"1,084",-,10/01/2023,09/30/2025,-
9,NATION,I_017_01_PPR_PD_N_TOO_SMALL,14,-,10/01/2023,09/30/2025,-
10,NATION,I_017_01_PPR_PD_N_WORSE_NATL,67,-,10/01/2023,09/30/2025,-

Emergency Department Volume and Capacity 2021–2023

This dataset provides the Emergency Department ratio of encounters and treatment stations to represent the ED Burden. Smaller ratios indicate fewer ED visits per available treatment station and less burden. Larger ratios of ED visits per available treatment station indicate greater burden. The encounters are broken down by health-related conditions: Active COVID-19, Asthma, Cancer, Cardiac, COPD, COVID-19 History, Diabetes, Homeless, Hypertension, Mental Health, Obesity, Pneumonia, Respiratory, Sepsis, Stroke, and Substance Abuse.

**1. OSHPD ID**
* A unique identification number assigned to each healthcare facility.

**2. Facility Name**

* The name of the hospital or healthcare facility.

**3. County Name**
* The county where the facility is located.

**4. System**
* The healthcare system or organization that the facility belongs to.

**5. Year**
* The year associated with the facility reported data.

**6. Licensed Bed Size**
* The facility number of licensed hospital beds,
grouped into a bed-size range.

**7. Hospital Ownership**
* The type of organization that owns or operates the hospital, such as government or nonprofit.

**8. Urban/Rural Designation**
* Identifies whether the facility is located in an urban or rural area.

**9. Teaching Designation**
* Identifies whether the hospital is classified as a teaching or non-teaching facility.

**10. Category**
* The category used to classify the emergency department data or patient visits.

**11. Total ED Number of Visits**
* The total number of emergency department visits reported by the facility.

**12. ED Stations**
* The number of treatment stations available in the facility emergency department.

**13. ED Diagnosis Count**
* The number of emergency department diagnoses recorded for the specified category.

**14. Latitude**
* The geographic latitude of the healthcare facility.

**15. Longitude**
* The geographic longitude of the healthcare facility.

**16. Primary Care Shortage Area**
* Indicates whether the facility is located in an area designated as having a shortage of primary care services.

**17. Mental Health Shortage Area**
* Indicates whether the facility is located in an area designated as having a shortage of mental health services.

**18. Visits Per Station**
* The number of emergency department visits relative to the number of available ED treatment stations.

In [9]:
ER_Dep='/content/HHA 507/ HW 1/emergency-department-volume-and-capacity-2021-2023.xlsx'
read_ER_Dep = pd.read_excel(ER_Dep)
read_ER_Dep.head(11)

,oshpd_id,FacilityName2,CountyName,system,year,LICENSED_BED_SIZE,HospitalOwnership,UrbanRuralDesi,TEACHINGDesignation,Category,Tot_ED_NmbVsts,EDStations,EDDXCount,LATITUDE,LONGITUDE,PrimaryCareShortageArea,MentalHealthShortageArea,Visits_Per_Station
0,106010735,Alameda Hospital,Alameda,Alameda Health System,2022,100-149,Government,Urban,Non-Teaching,Active COVID-19,13579,12.0,520,37.762660,-122.253991,No,No,43.333333
1,106010739,Alta Bates Summit Medical Center – Alta Bates ...,Alameda,Sutter Health,2022,300-499,Nonprofit,Urban,Non-Teaching,Active COVID-19,29760,22.0,1177,37.856450,-122.257430,No,No,53.500000
2,106010776,UC San Francisco Benioff Children's Hospital O...,Alameda,NaN,2022,150-199,Nonprofit,Urban,Teaching,Active COVID-19,35062,40.0,1822,37.837220,-122.267470,No,No,45.550000
3,106010846,Highland Hospital,Alameda,Alameda Health System,2022,200-299,Government,Urban,Non-Teaching,Active COVID-19,66095,53.0,2109,37.799250,-122.231380,No,No,39.792453
4,106010937,Alta Bates Summit Medical Center,Alameda,Sutter Health,2022,300-499,Nonprofit,Urban,Non-Teaching,Active COVID-19,29336,30.0,1325,37.821060,-122.262570,No,No,44.166667
5,106010987,Washington Hospital – Fremont,Alameda,NaN,2022,300-499,Government,Urban,Non-Teaching,Active COVID-19,43964,39.0,3013,37.558470,-121.980060,No,No,77.256410
6,106014050,Stanford Health Care Tri-Valley,Alameda,NaN,2022,150-199,Nonprofit,Urban,Non-Teaching,Active COVID-19,28620,17.0,1378,37.692060,-121.880950,No,No,81.058824
7,106014132,Kaiser Foundation Hospital – Fremont,Alameda,Kaiser Foundation Hospitals,2022,100-149,Nonprofit,Urban,Non-Teaching,Active COVID-19,38960,18.0,1487,37.550550,-121.974830,No,No,82.611111
8,106014233,Eden Medical Center,Alameda,Sutter Health,2022,100-149,Nonprofit,Urban,Non-Teaching,Active COVID-19,31062,22.0,1467,37.698377,-122.087406,No,No,66.681818
9,106014326,Kaiser Foundation Hospital – Oakland/Richmond,Alameda,Kaiser Foundation Hospitals,2022,300-499,Nonprofit,Urban,Non-Teaching,Active COVID-19,120088,80.0,4883,37.824020,-122.257910,No,No,61.037500
10,106014337,Kaiser Foundation Hospital – San Leandro,Alameda,Kaiser Foundation Hospitals,2022,200-299,Nonprofit,Urban,Non-Teaching,Active COVID-19,69343,40.0,2893,37.706110,-122.169170,No,No,72.325000

Hospital Supplier Diversity Plans
This dataset contains annual reports from eligible California hospitals on their procurement efforts with minority-, women-, LGBT-, and disabled veteran-owned businesses.


**1. HCAI ID**
* Unique identification number assigned to the healthcare facility by HCAI/OSHPD.

**2. Year**
* The year in which the supplier diversity data was reported.

**3. Hospital Name**
* The name of the hospital or healthcare facility.

**4. Urban/Rural Designation**
* Identifies whether the hospital is located in an urban or rural area.

**5. Require Certification**
* Indicates whether the hospital requires businesses to have diversity certification for Supplier Diversity reporting.

**6. County**
* The California county where the hospital is located.

**7. Hospital Ownership**
* Identifies the type of ownership or control of the hospital.

**8. Category**
* Identifies the diversity category of the business involved in procurement.

**9. Procurement**
* The amount or value of purchases or leases of supplies, services, equipment, or other eligible expenditures.

**10. Procurement Type**
* Identifies the specific type or classification of procurement being reported.

**11. Disproportionate Share Hospital**
* Indicates whether the hospital is designated as a Disproportionate Share Hospital (DSH).

In [10]:
Sup_div='/content/HHA 507/ HW 1/supplier-diversity-in-california-hospital-procurements-2021-2023-data-dictionary.xlsx'
read_Sup_div = pd.read_excel(Sup_div)
read_Sup_div.head(11)

,Field title,Field Name,Data Type,Description
0,HCAI_ID,HCAI ID,Number,"HCAI/OSHPD facility ID, full list here: https:..."
1,Year,Year,Number,Reporting year
2,Hospital_Name,Hospital Name,Text,Hospital name
3,Urban_Rural_Designation,Urban Rural Designation,Text,As determined by Medical Service Study Area De...
4,Require_Certification,Require Certification,Text,This denotes whether the hospital facility req...
5,County,County,Text,County
6,Hospital_Ownership,Hospital Ownership,Text,Licensee type of control
7,Category,Category,Text,This indicates diverse business enterprise cat...
8,Procurement,Procurement,Text,"The purchase or lease of supplies, services, e..."
9,Procurement_Type,Procurement Type,Text,This indicates the type of procurement
10,Disproportinate_Share_Hospital,Disproportinate Share Hospital,Text,Disproportionate Share Hospitals serve low-inc...

Unemployment dataset

This table contains data on the percent of the population in the labor force who are unemployed (unemployment rate), for California, its regions, counties, county divisions, cities/towns, and census tracts. Data is from the Local Area Unemployment Statistics (LAUS), Bureau of Labor Statistics (BLS), and the U.S. Census Bureau, American Community Survey (ACS).

**1. ind_id — Indicator ID**
* A unique identification number assigned to the indicator.

**2. ind_definition — Indicator Definition**
* A plain-language definition describing the indicator being measured.

**3. reportyear — Report Year**
* The year or range of years for which the indicator was reported.

**4. race_eth_code — Race/Ethnicity Code**
* A numeric code used to identify a specific race or ethnicity group.

**5. race_eth_name — Race/Ethnicity Name**
*The name of the race or ethnicity group associated with the data.

**6. geotype — Geographic Type**
* Identifies the type of geographic area represented, such as state, region, county, place, county division, or census tract.

**7. geotypevalue — Geographic Type Value**
* A geographic identification code used to identify the specific area, such as a FIPS, region, place, or census tract code.

**8. geoname — Geographic Name**
* The name of the geographic area represented by the record.

**9. county_name — County Name**
* The name of the county in which the geographic area is located.

**10. county_fips — County FIPS Code**
* A five-digit code used to uniquely identify a county.

**11. region_name — Region Name**
* The name of the MPO-based geographic region associated with the data.

**12. region_code — Region Code**
* A numeric code used to identify the MPO-based geographic region.

**13. Unemployment — Unemployed Population**
* The estimated number of people who are unemployed.

**14. Labor_force — Labor Force**
* The estimated number of people who are part of the labor force.

**15. Unemployment_rate — Unemployment Rate**
* The percentage of the labor force that is unemployed, calculated as unemployment divided by the labor force  100.

**16. ll_95ci — Lower 95% Confidence Interval**
* The lower limit of the 95% confidence interval for the unemployment rate.

**17. ul_95ci — Upper 95% Confidence Interval**
* The upper limit of the 95% confidence interval for the unemployment rate.

**18. se — Standard Error**
* The standard error of the unemployment rate estimate.

**19. rse — Relative Standard Error**
* A measure of the precision of the unemployment rate estimate relative to the size of the estimate.

**20. ca_decile — California Decile**
* Groups California geographic areas into 10 ranked categories based on their unemployment values.

**21. ca_rr — California Rate Ratio**
* Compares the unemployment rate for the geographic area with the overall California unemployment rate

**22. version — Version**
* The date and time indicating the version of the dataset.

In [11]:
Unemplo='/content/HHA 507/ HW 1/hci_unemployment_290_ca_re_co_cd_pl_ct-5-22-14-ada.xlsx'
read_Unemplo = pd.read_excel(Unemplo)
read_Unemplo.head(11)

,ind_id,ind_definition,reportyear,race_eth_code,race_eth_name,geotype,geotypevalue,geoname,county_fips,county_name,...,Unemployment,Labor_force,Unemployment_rate,ll_95ci,ul_95ci,se,rse,place_decile,ca_rr,version
0,290,Unemployment rate,2004,9.0,Total,CA,6.0,California,NaN,NaN,...,1089657.0,17444436.0,6.2,NaN,NaN,NaN,NaN,NaN,1.0,2014-05-22 11:47:47
1,290,Unemployment rate,2005,9.0,Total,CA,6.0,California,NaN,NaN,...,952559.0,17544763.0,5.4,NaN,NaN,NaN,NaN,NaN,1.0,2014-05-22 11:47:47
2,290,Unemployment rate,2006,9.0,Total,CA,6.0,California,NaN,NaN,...,865423.0,17686689.0,4.9,NaN,NaN,NaN,NaN,NaN,1.0,2014-05-22 11:47:47
3,290,Unemployment rate,2006-2010,1.0,AIAN,CA,6.0,California,NaN,NaN,...,9673.0,70286.0,13.8,12.608511,14.991489,0.607903,4.405092,NaN,1.0,2014-05-22 11:47:47
4,290,Unemployment rate,2006-2010,3.0,AfricanAm,CA,6.0,California,NaN,NaN,...,142776.0,1012992.0,14.1,13.742553,14.457447,0.182371,1.293410,NaN,1.0,2014-05-22 11:47:47
5,290,Unemployment rate,2006-2010,2.0,Asian,CA,6.0,California,NaN,NaN,...,175048.0,2452234.0,7.1,6.980851,7.219149,0.060790,0.856201,NaN,1.0,2014-05-22 11:47:47
6,290,Unemployment rate,2006-2010,4.0,Latino,CA,6.0,California,NaN,NaN,...,666317.0,6270852.0,10.6,10.480851,10.719149,0.060790,0.573493,NaN,1.0,2014-05-22 11:47:47
7,290,Unemployment rate,2006-2010,7.0,Multiple,CA,6.0,California,NaN,NaN,...,41077.0,320235.0,12.8,12.204255,13.395745,0.303951,2.374620,NaN,1.0,2014-05-22 11:47:47
8,290,Unemployment rate,2006-2010,5.0,NHOPI,CA,6.0,California,NaN,NaN,...,7636.0,69487.0,11.0,9.927660,12.072340,0.547112,4.973750,NaN,1.0,2014-05-22 11:47:47
9,290,Unemployment rate,2006-2010,8.0,Other,CA,6.0,California,NaN,NaN,...,5343.0,54725.0,9.8,8.608511,10.991489,0.607903,6.203089,NaN,1.0,2014-05-22 11:47:47
10,290,Unemployment rate,2006-2010,9.0,Total,CA,6.0,California,NaN,NaN,...,1642405.0,18274871.0,9.0,8.880851,9.119149,0.060790,0.675447,NaN,1.0,2014-05-22 11:47:47

MTA Colors

This dataset includes the RGB Hex code and CMYK values for the colors used by the MTA for its various services, including the New York City Subway, the Staten Island Railway, the Long Island Rail Road, Metro-North Railroad, and Bridges & Tunnels, and for the MTA logo itself.

**1. :id**
* A unique identifier assigned to each row in the dataset.

**2. :version**
* Identifies the version of the individual record.

**3. :created_at**
* The date and time when the record was created.

**4. :updated_at**
* The date and time when the record was last updated.

**5. operator**
* The MTA agency or transportation system that operates the service, such as New York City Subway, Long Island Rail Road, or Metro-North Railroad.

**6. service**
* The specific subway line, railroad branch, or transportation service associated with the color.

**7. hex_color**
* The official service color represented as a hexadecimal color code used for digital displays.

**8. cmyk**
* The official service color represented using Cyan, Magenta, Yellow, and Black (CMYK) values, commonly used for printing.

In [12]:
MTA_colors='/content/HHA 507/ HW 1/MTA_Data.json'
read_MTA_colors = pd.read_json(MTA_colors)
read_MTA_colors.head(11)

,:id,:version,:created_at,:updated_at,operator,service,hex_color,cmyk
0,row-6xi3.6w53-277j,rv-hf27.xhd3.7zb5,2026-09-25 15:05:58.452000+00:00,2026-09-25 15:05:58.452000+00:00,MTA,MTA,#08179C,"(100, 68, 0, 0)"
1,row-ejen-4kgr-5vsh,rv-vqa5~ca4s-kra6,2026-09-25 15:05:58.452000+00:00,2026-09-25 15:05:58.452000+00:00,MTA,ISA,#0078C6,"(100, 12, 0, 0)"
2,row-y9yx_jpji.5uce,rv-cyny_xi7v~kwa3,2026-09-25 15:05:58.452000+00:00,2026-09-25 15:05:58.452000+00:00,New York City Subway,"A,C,E",#0062CF,"(100, 30, 0, 0)"
3,row-a3bp.rd4x-gc4c,rv-hhvb_9xjv.6vzm,2026-09-25 15:05:58.452000+00:00,2026-09-25 15:05:58.452000+00:00,New York City Subway,"B,D,F,M",#EB6800,"(0, 57, 100, 0)"
4,row-smad-tdf7-5eze,rv-5xiy.wr5d-c442,2026-09-25 15:05:58.452000+00:00,2026-09-25 15:05:58.452000+00:00,New York City Subway,G,#799534,"(60, 7, 100, 0)"
5,row-p57q~5hwz~vdct,rv-tg9u~phre~7buw,2026-09-25 15:05:58.452000+00:00,2026-09-25 15:05:58.452000+00:00,New York City Subway,"J,Z",#8E5C33,"(40, 58, 100, 0)"
6,row-fcpg.29cv_zqw8,rv-mmck-sqpw-vqkh,2026-09-25 15:05:58.452000+00:00,2026-09-25 15:05:58.452000+00:00,New York City Subway,L,#7C858C,"(0, 0, 0, 50)"
7,row-bcw9-t7mm-89tf,rv-kf7g.5tdh_tkmu,2026-09-25 15:05:58.452000+00:00,2026-09-25 15:05:58.452000+00:00,New York City Subway,"N,Q,R,W",#F6BC26,"(0, 15, 100, 0)"
8,row-r6dh.n4rg_wgue,rv-5dtk_tn83_sdk6,2026-09-25 15:05:58.452000+00:00,2026-09-25 15:05:58.452000+00:00,New York City Subway,S,#7C858C,"(0, 0, 0, 50)"
9,row-64cv~c7ed_rcc4,rv-qiii_c52f~wtie,2026-09-25 15:05:58.452000+00:00,2026-09-25 15:05:58.452000+00:00,New York City Subway,T,#008EB7,"(100, 0, 20, 0)"
10,row-gjst.nek5~nma3,rv-mggv~j3ec-tk4x,2026-09-25 15:05:58.452000+00:00,2026-09-25 15:05:58.452000+00:00,New York City Subway,"1,2,3",#D82233,"(0, 100, 65, 0)"

MTA Subway Trains Delayed
This dataset shows the number of subway trains delayed per day type (weekdays and weekends) in a month, broken down into specific delay categories.

**1. :id**
* A unique identifier assigned to each record in the dataset.

**2. :version**
*Identifies the version of the individual record.

**3. :created_at**
* The date and time when the record was created in the dataset.

**4. :updated_at**
* The date and time when the record was last updated.

**5. month**
* The month and year associated with the reported subway delay data.

**6. division**
* Identifies the subway division associated with the line, such as A Division or B Division.

**7. line**
* Identifies the specific subway line associated with the delay data.

**8. day_type**
* Identifies the type of day associated with the delay data, such as weekday or weekend.

**9. reporting_category**
* Identifies the general cause of the delays, such as crew availability, infrastructure and equipment, operating conditions, external factors, police and medical incidents, or planned right-of-way (ROW) work.

**10. delays**
* The number of subway delays reported for the specified month, line, day type, and reporting category.

In [13]:
MTA_delay='/content/HHA 507/ HW 1/MTA delays.json'
read_MTA_delay = pd.read_json(MTA_delay)
read_MTA_delay.head(11)

,:id,:version,:created_at,:updated_at,month,division,line,day_type,reporting_category,delays
0,row-4zdc-fbtt~q6ri,rv-f3mi~jikw_8kfn,2026-09-25 15:24:45.618000+00:00,2026-09-25 15:24:45.618000+00:00,2020-01-01T00:00:00.000,A DIVISION,1,1,Crew Availability,17
1,row-38i8~2zs2_5dvs,rv-va3j-z8wp~tfzi,2026-09-25 15:24:45.618000+00:00,2026-09-25 15:24:45.618000+00:00,2020-01-01T00:00:00.000,A DIVISION,1,1,Infrastructure & Equipment,400
2,row-u7we_ira8~njfj,rv-dxcv~umrg.v6bs,2026-09-25 15:24:45.618000+00:00,2026-09-25 15:24:45.618000+00:00,2020-01-01T00:00:00.000,A DIVISION,1,1,Operating Conditions,332
3,row-q9ph~up4f~3pdf,rv-dh2c.hy59.kee6,2026-09-25 15:24:45.618000+00:00,2026-09-25 15:24:45.618000+00:00,2020-01-01T00:00:00.000,A DIVISION,1,1,External Factors,314
4,row-4h9a_chuq_j9pf,rv-zkif~ynwg.4m4t,2026-09-25 15:24:45.618000+00:00,2026-09-25 15:24:45.618000+00:00,2020-01-01T00:00:00.000,A DIVISION,1,1,Police & Medical,345
5,row-4vbp.brur_v5pa,rv-zjqh~vfhg.6gwh,2026-09-25 15:24:45.618000+00:00,2026-09-25 15:24:45.618000+00:00,2020-01-01T00:00:00.000,A DIVISION,1,1,Planned ROW Work,111
6,row-5stu~n2aw.5esj,rv-vkwj-bes7_cczh,2026-09-25 15:24:45.618000+00:00,2026-09-25 15:24:45.618000+00:00,2020-01-01T00:00:00.000,A DIVISION,1,2,Crew Availability,10
7,row-254u-5mwk_yg7p,rv-b9qa~976x.t7ni,2026-09-25 15:24:45.618000+00:00,2026-09-25 15:24:45.618000+00:00,2020-01-01T00:00:00.000,A DIVISION,1,2,Planned ROW Work,18
8,row-gjjw.p62p_aa5i,rv-c9sf~wksa-9tb3,2026-09-25 15:24:45.618000+00:00,2026-09-25 15:24:45.618000+00:00,2020-01-01T00:00:00.000,A DIVISION,1,2,Police & Medical,42
9,row-3rnk~d4b2-b7de,rv-skqz-mjdp.68mh,2026-09-25 15:24:45.618000+00:00,2026-09-25 15:24:45.618000+00:00,2020-01-01T00:00:00.000,A DIVISION,1,2,Infrastructure & Equipment,78
10,row-wq6y.56jw-7sxm,rv-6fjz-s8zy~vyqw,2026-09-25 15:24:45.618000+00:00,2026-09-25 15:24:45.618000+00:00,2020-01-01T00:00:00.000,A DIVISION,1,2,Operating Conditions,36

MTA LIRR Major Incidents

This dataset is of major incidents on the LIRR, which are defined as events that lead to ten or more trains that are delayed by more than 5 minutes 59 seconds, canceled, or terminated.

**1. :id**
* A unique identifier assigned to each record in the dataset.

**2. :version**
* Identifies the version of the individual record.

**3. :created_at**
The date and time when the record was created in the dataset.

**4. :updated_at**
* The date and time when the record was last updated.

**5. date**
* The date when the LIRR incident occurred.

**6. event_description**
* A description of the incident or event that affected LIRR train service.

**7. am_peak_late**
* The number of trains that were late during the AM peak period.

**8. am_peak_canceled**
* The number of trains that were canceled during the AM peak period.

**9. am_peak_terminated**
* The number of trains that were terminated before reaching their scheduled destination during the AM peak period.

**10. pm_peak_late**
* The number of trains that were late during the PM peak period.

**11. pm_peak_canceled**
* The number of trains that were canceled during the PM peak period.

**12. pm_peak_terminated**
* The number of trains that were terminated before reaching their scheduled destination during the PM peak period.

**13. off_peak_late**
* The number of trains that were late during off-peak periods.

**14. off_peak_canceled**
* The number of trains that were canceled during off-peak periods.

**15. off_peak_terminated**
* The number of trains that were terminated before reaching their scheduled destination during off-peak periods.

In [14]:
MTA_LIRR ='/content/HHA 507/ HW 1/MTA_LIRR incidents.json'
read_MTA_LIRR = pd.read_json(MTA_LIRR)
read_MTA_LIRR.head(11)

,:id,:version,:created_at,:updated_at,date,event_description,am_peak_late,am_peak_canceled,am_peak_terminated,pm_peak_late,pm_peak_canceled,pm_peak_terminated,off_peak_late,off_peak_canceled,off_peak_terminated
0,row-8zan_rthe_mpnw,rv-rit9_exzn.b784,2026-09-25 15:53:17.305000+00:00,2026-09-25 15:53:17.305000+00:00,2020-01-03,Amtrak related track condition,0,0,0,3,0,0,7,0,0
1,row-7hb3~juw6.pjyb,rv-z68e.njks~fkdr,2026-09-25 15:53:17.305000+00:00,2026-09-25 15:53:17.305000+00:00,2020-01-03,Motor vehicle accident interfered with train m...,21,5,0,0,0,0,5,1,0
2,row-fg2k_57e5~qswy,rv-fyhj-yt8s_2b4r,2026-09-25 15:53:17.305000+00:00,2026-09-25 15:53:17.305000+00:00,2020-01-04,Main Line expansion track program,0,0,0,0,0,0,13,0,0
3,row-n79i~z55k.hg4v,rv-5c94~bsmm.fjwa,2026-09-25 15:53:17.305000+00:00,2026-09-25 15:53:17.305000+00:00,2020-01-06,Track condition at Lindenhurst Station,5,1,0,0,0,0,8,2,1
4,row-5yk5~qwpq_x8y9,rv-vtqe_gfyp~2tq8,2026-09-25 15:53:17.305000+00:00,2026-09-25 15:53:17.305000+00:00,2020-01-08,Multiple track conditions between Valley and D...,13,0,0,2,0,0,6,0,0
5,row-ng3b-7zzm_pvxs,rv-n7w9.hj7v~7hig,2026-09-25 15:53:17.305000+00:00,2026-09-25 15:53:17.305000+00:00,2020-01-09,Multiple track conditions between Valley and D...,2,0,0,1,0,0,12,0,0
6,row-3sn8-eayg_xtfj,rv-snxu~nb8g_6xpz,2026-09-25 15:53:17.305000+00:00,2026-09-25 15:53:17.305000+00:00,2020-01-11,Main Line expansion track program,0,0,0,0,0,0,19,0,0
7,row-fmdg.dtzb-8fjr,rv-9jkg.pef3-tbvs,2026-09-25 15:53:17.305000+00:00,2026-09-25 15:53:17.305000+00:00,2020-01-12,Trespasser fatality west of Merillon Ave Station,0,0,0,0,0,0,13,10,11
8,row-d4ye-p6g6.3p5p,rv-nprz_mrx9_tynk,2026-09-25 15:53:17.305000+00:00,2026-09-25 15:53:17.305000+00:00,2020-01-13,Switch trouble west of Ronkonkoma Station,10,0,0,0,0,0,2,0,0
9,row-fh6c.8hd3-pgqx,rv-rkh9_94xw-dwsx,2026-09-25 15:53:17.305000+00:00,2026-09-25 15:53:17.305000+00:00,2020-01-14,Amtrak related track condition,9,0,0,0,0,0,1,0,0
10,row-699y.86m4.g8zu,rv-7h9c_ki85~28c5,2026-09-25 15:53:17.305000+00:00,2026-09-25 15:53:17.305000+00:00,2020-01-14,Train 566 with equipment trouble at Floral Par...,0,0,0,6,0,1,4,1,0